### ISSUE TITLE
Base Code

### ISSUE THREAD

**Issue by Kenna-Chase** [theagencyteam3021/2019BattleOfTheBorder#1]
Current:
- 3 Motor Drive Motors to Speed Controller Group
- Ball Shooter 1 motor
- Ball Loader 1 motor
- Solenoid for adjusting height of ball shooter (pneumatic)
Hopeful: 
- Limelight camera (minimal) just camera
-Potential alignment code

In Autonomous mode: 
- Drop the ball loader solenoid (double acting) (normal position should be open)
- Drive off of ramp
Autonomous mode could be also done in teleop if need be.

**Comment by rajpabari** [comment]
Added as separate issues
